### ISSUE TITLE
Injected/Browser wallet not selectable in sign in modal

### ISSUE THREAD

**Issue by beemeeupnow** [guildxyz/guild.xyz#1161]
### Describe the bug

This worked fine several months ago so regression was introduced recently.

When using a non-MetaMask injected browser extension wallet, there is no ability to select it in the modal.

### To Reproduce

In my case, I _only_ have Taho wallet installed and confirmed that window.ethereum is properly populated.

Browse to https://guild.xyz/explorer and click the "Sign in" button in the top right of the page.

No option presented to connect with generic ethereum injected browser wallet. (MetaMask option also not present, which has historically been usable as a workaround)

### Expected Behavior

Ideally, Taho should show up as a selectable option. (it is in the major connector libraries)

When #474 was resolved, at least choosing MetaMask was working, but now even that doesn't show up as a choice.

At worst, when an unrecognized wallet is available at window.ethereum the user should be able to "Browser Wallet", "Injected Wallet" or similar.

### Which browser are you using? (if relevant)

Chrome

**Comment by BrickheadJohnny** [comment]
Hello!
Thank you so much for the detailed report. We display all detected EIP-6963 compatible wallets, but [seems like](https://github.com/tahowallet/extension/issues/3725) Tally Ho doesn't support this cool new standard yet, that's why you can't see it in the wallet selector modal. I just added a fallback option in case we can't detect any EIP-6963 compatible connectors (but `window.ethereum` is populated), so you should be able to connect using that from now.

Please feel free to reopen the issue if you still experience any related issues.

**Comment by beemeeupnow** [comment]
Glad to see EIP-6963 being adopted!
 
Yes, it's much better UX to have the fallback and I appreciate the quick response and solution!
