### ISSUE TITLE
i cant connect my discord 

### ISSUE THREAD

**Issue by patrickliobianca** [guildxyz/guild.xyz#1165]
### Describe the bug

when i press connect the pop up opens and i can press connect but it takes forever and it doesn't connect i have tried restarting and everything but it just doesn't work

### To Reproduce

![Screenshot (204)](https://github.com/guildxyz/guild.xyz/assets/166997593/b4339246-2fb4-4948-8420-6b5b3a40246b)

### Expected Behavior

-

### Which browser are you using? (if relevant)

chrome

**Comment by BrickheadJohnny** [comment]
Hello, this is an issue on Discord's side, so unfortunately we can't really do anything about it. Please try again later & let us know if it works!

**Comment by LouisVA** [comment]
This has been like this for multiple months. On top of that guild.xyz makes me need to verify my wallet every... 40s?

I wish all apps stopped using guild.xyz. The amount of lost time on your app is ridiculous.

**Comment by BrickheadJohnny** [comment]
> This has been like this for multiple months. On top of that guild.xyz makes me need to verify my wallet every... 40s?
> 
> I wish all apps stopped using guild.xyz. The amount of lost time on your app is ridiculous.

@LouisVA 
This is certainly not the expected behavior & our goal is to provide the best possible experience for our users, but keep in mind that we work with many 3rd party providers which are out of our control - Discord is a great example.
We collect important error logs, so next time you experience this kind of issue (verify wallet modal shows up too many times), please contact our support team by clicking on the Intercom widget on our website.

<img width="169" alt="image" src="https://github.com/guildxyz/guild.xyz/assets/92519134/8dd7640a-3464-4c93-8c2b-72259cd94a33">

We may ask for more details there, but I am sure that we'll eventually solve the issue.
